import io.testgrid.listeners.TestListener;
import io.testgrid.listeners.RetryFailedTestCases;
import io.testgrid.tg;
import org.testng.annotations.*;
import app.getxray.xray.testng.annotations.XrayTest;
import io.testgrid.enums.ComparisonType;
import org.json.JSONObject;
import io.testgrid.enums.Direction;
import io.testgrid.enums.Size;
import io.testgrid.enums.Buttons;
import static io.testgrid.baseClass.driver;
import org.openqa.selenium.*;
import static io.testgrid.enums.KeyboardKeys.*;
import org.openqa.selenium.support.ui.Select;
import java.net.*;
import java.util.*;
import java.io.*;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

@Listeners(TestListener.class);
public class dfgdfg {

	@Test(retryAnalyzer = RetryFailedTestCases.class)
	public void dfgdfg() {
		tg.openBrowser();
				tg.wait("ele_r1h6kqsqpp077", ComparisonType.IS_VISIBLE);
				tg.click("ele_r1h6kqsqpp077", 1);
				tg.wait("ele_r1h6kqsqpp077", ComparisonType.IS_VISIBLE);
				tg.type("ele_r1h6kqsqpp077", "gdfgdfgfdg");
				tg.wait("ele_r1hmkqsqpp255", ComparisonType.IS_VISIBLE);
				tg.click("ele_r1hmkqsqpp255", 1);
				tg.wait("ele_r1hmkqsqpp255", ComparisonType.IS_VISIBLE);
				tg.typeEncrypted("ele_r1hmkqsqpp255", "MARV+uuUXgw5RKjCQK8OJg==:MTIzNDU2Nzg5MTAxMTEyMQ==");
				tg.wait("ele_r1hmkqsqpp255", ComparisonType.IS_VISIBLE);
				tg.click("ele_r1hmkqsqpp255", 1);
				tg.wait("ele_login205", ComparisonType.IS_VISIBLE);
				tg.click("ele_login205", 1);
				tg.wait("ele_login205", ComparisonType.IS_VISIBLE);
				tg.click("ele_login205", 1);
				tg.wait("ele_createnewa666", ComparisonType.IS_VISIBLE);
				tg.click("ele_createnewa666", 1);
				tg.wait("ele_r1cl2p4jik458", ComparisonType.IS_VISIBLE);
				tg.click("ele_r1cl2p4jik458", 1);
				tg.wait("ele_r1cl2p4jik458", ComparisonType.IS_VISIBLE);
				tg.type("ele_r1cl2p4jik458", "dgdfgdfg");
				tg.wait("ele_r1cl2p4jik458", ComparisonType.IS_VISIBLE);
				tg.click("ele_r1cl2p4jik458", 1);
				tg.wait("ele_r1cl2p4jik458", ComparisonType.IS_VISIBLE);
				tg.type("ele_r1cl2p4jik458", "dfgfdgdfg");
				tg.wait("ele_dateofbirt604", ComparisonType.IS_VISIBLE);
				tg.click("ele_dateofbirt604", 1);
				tg.wait("ele_div534", ComparisonType.IS_VISIBLE);
				tg.click("ele_div534", 1);
				tg.wait("ele_day599", ComparisonType.IS_VISIBLE);
				tg.click("ele_day599", 1);
				tg.wait("ele_february741", ComparisonType.IS_VISIBLE);
				tg.click("ele_february741", 1);
				tg.wait("ele_monthfebru577", ComparisonType.IS_VISIBLE);
				tg.click("ele_monthfebru577", 1);
				tg.wait("ele_june595", ComparisonType.IS_VISIBLE);
				tg.click("ele_june595", 1);
				tg.wait("ele_year596", ComparisonType.IS_VISIBLE);
				tg.click("ele_year596", 1);
				tg.wait("ele_div487", ComparisonType.IS_VISIBLE);
				tg.click("ele_div487", 1);
				tg.wait("ele_r6ad8p4jik929", ComparisonType.IS_VISIBLE);
				tg.click("ele_r6ad8p4jik929", 1);
				tg.wait("ele_r6ad8p4jik929", ComparisonType.IS_VISIBLE);
				tg.type("ele_r6ad8p4jik929", "dfdfdfg");
				tg.wait("ele_bytappings796", ComparisonType.IS_VISIBLE);
				tg.click("ele_bytappings796", 1);
				tg.wait("ele_privacypol067", ComparisonType.IS_VISIBLE);
				tg.click("ele_privacypol067", 1);
				tg.wait("ele_getstarted648", ComparisonType.IS_VISIBLE);
				tg.click("ele_getstarted648", 1);
				tg.wait("ele_englishukm129", ComparisonType.IS_VISIBLE);
				tg.click("ele_englishukm129", 1);
				tg.wait("ele_englishukm129", ComparisonType.IS_VISIBLE);
				tg.type("ele_englishukm129", "fdgdfgdfg");
				tg.wait("ele_ialreadyha304", ComparisonType.IS_VISIBLE);
				tg.click("ele_ialreadyha304", 1);
				tg.wait("ele_ialreadyha304", ComparisonType.IS_VISIBLE);
				tg.type("ele_ialreadyha304", "fdgdfgdfgfdg");
				tg.wait("ele_englishukm415", ComparisonType.IS_VISIBLE);
				tg.click("ele_englishukm415", 1);
				tg.wait("ele_englishukm678", ComparisonType.IS_VISIBLE);
				tg.click("ele_englishukm678", 1);
				tg.wait("ele_ialreadyha696", ComparisonType.IS_VISIBLE);
				tg.click("ele_ialreadyha696", 1);
				tg.wait("ele_theprivacy894", ComparisonType.IS_VISIBLE);
				tg.click("ele_theprivacy894", 1);
				tg.wait("ele_theprivacy902", ComparisonType.IS_VISIBLE);
				tg.click("ele_theprivacy902", 1);
				tg.wait("ele_theprivacy894", ComparisonType.IS_VISIBLE);
				tg.click("ele_theprivacy894", 1);
				tg.wait("ele_bytappings796", ComparisonType.IS_VISIBLE);
				tg.click("ele_theprivacy894", 1);
		tg.close();
	}
}